# Generated by Django 4.2.11 on 2024-03-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.category'),
        ),
    ]
