# Generated by Django 4.2.11 on 2024-03-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_subcategory_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.subcategory'),
        ),
    ]
