# Generated by Django 4.2.11 on 2024-03-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_recipe_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hello.subcategory'),
        ),
    ]
